### ISSUE TITLE
The coco dataset

### ISSUE THREAD

**Issue by ghost** [sidward14/Style-AttnGAN#18]
Have you trained this repo on the coco dataset ? Can this repo be trained on the coco dataset ? Thanks

**Comment by sidward14** [comment]
Sorry was out of town!

Answers are yes and yes. But I didn't store the coco model, sorry!

**Comment by ghost** [comment]
Thanks for your help.

**Comment by ghost** [comment]
How much GPU memory did you use, and how long did it take to train on the COCO dataset for both DAMSM and AttnGAN models? Thanks

**Comment by sidward14** [comment]
Sorry, I don't really remember the GPU RAM usage for coco. But since GPU RAM usage comes from the inputs and model, you can make it the same GPU RAM usage as the bird dataset by adjusting hyperparameters.

As I recall, it took longer to converge when training on the coco dataset (compared to bird), which makes sense since the data distribution is much more varied.

**Comment by ghost** [comment]
Thanks for your help.
